apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gotham-ui-application-set
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - env: dev
        autoSync: true
        prune: true
        selfHeal: true
      - env: qa
        autoSync: true
        prune: true
        selfHeal: true
      - env: prod
        autoSync: fasle
  template:
    metadata:
      name: 'nginx-{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/nick-draper/app-set.git
        targetRevision: '{{ if eq .env "prod" }}main{{ else }}{{.env}}{{ end }}'
        path: nginx
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if eq .env "prod" }}nginx{{ else }}nginx-{{.env}}{{ end }}'
  templatePatch: |
    spec:
    {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .prune }}
          selfHeal: {{ .selfHeal }}
    {{- end }}
