apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-qa
  template:
    metadata:
      labels:
        app: nginx-qa
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
